swagger: '2.0'
info:
  description: OperatorFabric ThirdParty Management API
  version: 0.13.1.RELEASE
  title: Thirds Management
  termsOfService: ''
  contact:
    email: opfab-maintainers_AT_rte-france.com
    url: 'https://opfab.github.io/'
  license:
    name: Mozilla Public License V2.0
    url: 'http://mozilla.org/MPL/2.0/'
host: localhost
basePath: /apis
tags:
  - name: thirds
    description: Everything concerning specified Third
schemes:
  - http
paths:
  /thirds:
    get:
      tags:
        - thirds
      summary: List existing Thirds
      description: List existing Thirds
      operationId: getThirds
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Third'
        '401':
          description: Authentication required
    post:
      tags:
      - thirds
      summary: Uploads Third configuration bundle
      description: >-
        Uploads Third configuration bundle. Bundle is a gzipped tarball (tar.gz)
        containing a config.json file and resource file using the following
        layout:

        ```

        └──css

        └──i18n

        │   └──en.json

        │   └──fr.json

        │   └...

        └──media

        │   └──sound1.wav

        │   └──sound2.ogg

        └──template

        │   └──en

        │   |  └──emergency.handlebars

        │   |  └──info.handlebars

        │   └──fr

        │   |  └──emergency.handlebars

        │   |  └──info.handlebars

        │   └...

        └──config.json

        ```

        The config.json file contains a Third object in json notation (see
        [Models](#__Models))
      operationId: uploadBundle
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - name: file
        in: formData
        description: file to upload
        required: true
        type: file
      responses:
        '201':
          description: Successful creation
          schema:
            $ref: '#/definitions/Third'
        '401':
          description: Authentication required
        '403':
          description: Forbidden - ADMIN role necessary
  '/thirds/{thirdName}':
    get:
      tags:
        - thirds
      summary: Access existing Third data
      description: Access existing Third data
      operationId: getThird
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of template (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Third'
        '401':
          description: Authentication required
  '/thirds/{thirdName}/templates/{templateName}':
    get:
      tags:
        - thirds
      summary: Get existing template associated with Third
      description: >-
        Get template associated with Third, if file exists return file
        (application/handlebars) otherwise return error message
        (application/json)
      operationId: getTemplate
      produces:
        - application/json
        - application/handlebars
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: false
          type: string
        - name: templateName
          in: path
          description: Name of template to retrieve (w.o. extension)
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of template (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
        '401':
          description: Authentication required
  '/thirds/{thirdName}/css/{cssFileName}':
    get:
      tags:
        - thirds
      summary: Get css file associated with Third
      description: >-
        Get css file associated with Third, if file exists return file
        (text/css) otherwise return error message (application/json)
      operationId: getCss
      produces:
        - application/json
        - text/css
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: cssFileName
          in: path
          description: Name of stylesheet file to retrieve (w.o. extension)
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of stylesheet (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
        '401':
          description: Authentication required
        '403':
          description: Forbidden - ADMIN role necessary
  '/thirds/{thirdName}/media/{mediaFileName}':
    get:
      tags:
        - thirds
      summary: Get media file associated with Third
      description: >-
        Get media file associated with Third, if file exists return file
        (audio/*) otherwise return error message (application/json)
      operationId: getMedia
      produces:
        - application/json
        - audio/*
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: mediaFileName
          in: path
          description: Name of media file to retrieve  (w.o. extension)
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: false
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of media (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
        '401':
          description: Authentication required
  '/thirds/{thirdName}/i18n':
    get:
      tags:
        - thirds
      summary: Get i18n file associated with Third
      description: >-
        Get i18n file associated with Third, if file exists return file
        (text/plain) otherwise return error message (application/json)
      operationId: getI18n
      produces:
        - application/json
        - text/plain
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: locale
          in: query
          description: Locale iso code
          required: true
          type: string
        - name: version
          in: query
          required: false
          description: Expected version of i18n (defaults to latest)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
        '404':
          description: No such template
        '401':
          description: Authentication required
  '/thirds/{thirdName}/{process}/{state}/details':
    get:
      tags:
        - thirds
      summary: Get details associated to thirds
      description: >-
        Get details associated with Third+process+state, returns an array of details (application/json)
      operationId: getDetails
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: process
          in: path
          description: Name of state
          required: true
          type: string
        - name: state
          in: path
          description: Name of state
          required: true
          type: string
        - name: apiVersion
          in: query
          required: false
          description: Expected version of third
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Detail'
        '404':
          description: No such third
        '401':
          description: Authentication required
  '/thirds/{thirdName}/{process}/{state}/actions':
    get:
      tags:
        - thirds
      summary: Get actions associated to thirds
      description: >-
        Get actions associated with Third+process+state, returns an array of actions (application/json)
      operationId: getActions
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: process
          in: path
          description: Name of state
          required: true
          type: string
        - name: state
          in: path
          description: Name of state
          required: true
          type: string
        - name: apiVersion
          in: query
          required: false
          description: Expected version of third
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              $ref: '#/definitions/Action'
        '404':
          description: No such third
        '401':
          description: Authentication required
  '/thirds/{thirdName}/{process}/{state}/actions/{actionKey}':
    get:
      tags:
        - thirds
      summary: Get actions associated to thirds
      description: >-
        Get actions associated with Third+process+state, returns an array of actions (application/json)
      operationId: getAction
      produces:
        - application/json
      parameters:
        - name: thirdName
          in: path
          description: Name of Third to retrieve
          required: true
          type: string
        - name: process
          in: path
          description: Name of state
          required: true
          type: string
        - name: state
          in: path
          description: Name of state
          required: true
          type: string
        - name: actionKey
          in: path
          description: Name of state
          required: true
          type: string
        - name: apiVersion
          in: query
          required: false
          description: Expected version of third
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Action'
        '404':
          description: No such third
        '401':
          description: Authentication required
definitions:

  ActionEnum:
    type: string
    description: |-
      Action type >
      * INTERNAL - Internal OperatorFabric action
      * URL - Uri based action
      * JNLP - Uri based jnlp action
    enum:
      - INTERNAL
      - URL
      - JNLP
    example: URL
  InputEnum:
    type: string
    description: |-
      Input type >
      * TEXT - A simple text input (size not limited)
      * LONGTEXT - A long text input (size not limited)
      * BOOLEAN - A boolean input
      * LIST - A list with one selectable value
      * MULTI_LIST - A list with multiple selectable values
      * SWITCH_LIST - Two lists with exchangeable values
      * STATIC - A static non editable parameter
    enum:
      - TEXT
      - LONGTEXT
      - BOOLEAN
      - LIST
      - MULTI_LIST
      - SWITCH_LIST
      - STATIC
    example: TEXT
  
  ThirdMenuEntry:
    type: object
    properties:
      id:
        type: string
        description: unique identifier of this menu item for the current third service
      url:
        type: string
        description: url of the endpoint for this menu item
      label:
        type: string
        description: >-
          i18n key for the label of this menu item.
          The value attached to this key should be defined in each XX.json file in the i18n folder of the bundle (where XX stands for the locale iso code, for example 'EN')


  Third:
    type: object
    description: >-
      Third party business module configuration. Models Third party properties
      and list referenced resources.
    properties:
      name:
        type: string
        description: Third party business module name
      version:
        type: string
        description: Third party business module configuration version
      templates:
        type: array
        description: List of templates name (without extension)
        example: '"emergency", "security"'
        items:
          type: string
      csses:
        type: array
        description: List of css file names (without extension)
        example: tab-style
        items:
          type: string
      i18nLabelKey:
        description: >-
          i18n key for the label of this Third
          The value attached to this key should be defined in each XX.json file in the i18n folder of the bundle (where XX stands for the locale iso code, for example 'EN')
        type: string
      medias:
        type: object
        description: List available medias
        additionalProperties:
          type: object
          properties:
            name:
              type: string
              description: media name
            files:
              type: array
              description: list of associated media files (with extension)
              example: jingle-bells.ogg
              items:
                type: string
      menuEntries:
        type: array
        description: describes the menu items to add to UI navbar
        items:
          $ref: '#/definitions/ThirdMenuEntry'
      processes:
        type: object
        additionalProperties:
          type: object
          properties:
            states: 
              type: object
              additionalProperties:
                type: object
                properties:
                  details:
                    type: array
                    description: List of card associated details
                    items:
                      $ref: '#/definitions/Detail'
                  actions:
                    type: object
                    description: 'Map of actions, identifying an action by its unique card related id'
                    additionalProperties:
                      $ref: '#/definitions/Action'
    required:
      - name
      - version
    example:
      name: My ThirdParty Application
      version: v1.0
      templates:
        - "emergency"
        - "info"
      csses:
        - "tab-style"
        - "content-style"
      i18nLabelKey: myThirdPartyApp.label
      medias:
        JingleBells:
          name: Jingle Bells
          files:
            - jingle-bells.ogg
            - vive-le-vent.ogg
        Alarm:
          name: Alarm sound
          files:
            - smallProblem.ogg
            - biggerProblem.ogg
            - abandonShip.ogg
      menuEntries:
        - id: website
          url: http://www.mythirdpartyapp.com
          label: menu.website
        - id: status
          url: http://www.mythirdpartyapp.com/status
          label: menu.status
      processes:
        process1:
          state1:
            details:
              - title:
                  key: template.title
                  parameters:
                    param: value
                titleStyle: titleClass
                templateName: template1
            actions:
              action1:
                type: URL
                lockAction: true
                lockCard: true
                needsConfirm: false
                called: false
                updateState: false
                updateStateBeforeAction: false
                hidden: true
                contentStyle: buttonContentClass
                buttonStyle: buttonClass
                label:
                  key: my.card.my.action.label
                inputs:
                  - type: LIST
                    label:
                      key: myCard.myAction.myInput1.label
                      parameters:
                        EN: Colours
                        FR: Couleurs
                    mandatory: true
                    name: selectedColour
                    value:
                      value: '#000000'
                      label:
                        key: black
                        parameters:
                          EN: Paint It Black
                          FR: Broyer du noir
                    values:
                      - value: '#000000'
                        label:
                          key: black
                          parameters:
                            EN: Paint It Black
                            FR: Broyer du noir
                      - value: '#51CE1E'
                        label:
                          key: green
                          parameters:
                            EN: Go Green
                            FR: Se mettre au vert
                  - type: LONGTEXT
                    label:
                      key: myCard.myAction.myInput2.label
                      parameters:
                        EN: Comment
                        FR: Commentaire
                    mandatory: false
                    name: comment
                    value: ''
                    maxLength: 250
                    rows: 10
          state2:
            details:
              - title:
                  key: template2.title
                  parameters:
                    param: value
                titleStyle: titleClass2
                templateName: template2
                styles:
                  - my-template.css
        process2:
          state1:
            details:
              - title:
                  key: template.title
                  parameters:
                    param: value
                titleStyle: titleClass
                templateName: template3
                styles:
                  - my-template.css
          state2:
            details:
              - title:
                  key: template2.title
                  parameters:
                    param: value
                titleStyle: titleClass2
                templateName: template4
                styles:
        
  I18n:
    type: object
    description: describes an i18n label
    properties:
      key:
        type: string
        description: i18n client side key
      parameters:
        type: object
        description: Optional parameters
        additionalProperties:
          type: string
    example:
      key: title
      parameters:
        EN: My Title
        FR: Mon Titre
        
  Detail:
    description: detail defines html data rendering
    type: object
    properties:
      title:
        description: Card i18n title
        $ref: '#/definitions/I18n'
      titleStyle:
        description: css classes applied to title
        type: string
      templateName:
        description: >-
          template unique name as defined by Third Party Bundle in Third Party
          Service
        type: string
      styles:
        description: >-
          css files names to load as defined by Third Party Bundle in Third
          Party Service
        type: array
        items:
          type: string
    example:
      title:
        key: template.title
        parameters:
          param: value
      titleStyle: titleClass
      templateName: template1
      styles:
        - bundleTest.css
        - otherStyle.css
          
  Action:
    description: defines an action on the business process associated to the card
    type: object
    properties:
      type:
        description: Action type
        $ref: '#/definitions/ActionEnum'
      url:
        description: Url of remtote service entry point
        type: string
      lockAction:
        type: boolean
        default: false
        description: 'if true, action will be locked after clicked client-side'
      lockCard:
        type: boolean
        default: false
        description: 'if true, all card action will be locked after clicked client-side'
      needsConfirm:
        type: boolean
        default: false
        description: 'if true, a confirmation will be asked before execution client-side'
      called:
        type: boolean
        default: false
        readOnly: true
        description: True if action has already been called at least once
      updateState:
        type: boolean
        default: false
        description: >-
          If true, client will attempt an update of ActionStatus before
          rendering
      updateStateBeforeAction:
        type: boolean
        default: false
        description: >-
          if true, client will attempt an update of ActionStatus before
          execution
      hidden:
        type: boolean
        default: false
        description: This action is hidden from card and is only available to details;
      contentStyle:
        type: string
        description: css classes of action button content (a &lt;i&gt; tag)
      buttonStyle:
        type: string
        description: css classes of action button
      label:
        description: 'button default label, appears as a tooltip'
        $ref: '#/definitions/I18n'
      inputs:
        description: >-
          list of action input parameters, generate a popup form upon action
          call
        type: array
        items:
          $ref: '#/definitions/Input'
    required:
      - type
      - label
    example:
      type: URL
      lockAction: true
      lockCard: true
      needsConfirm: false
      called: false
      updateState: false
      updateStateBeforeAction: false
      hidden: true
      contentStyle: buttonContentClass
      buttonStyle: buttonClass
      label:
        key: myCard.myAction.label
        parameters:
          EN: Choose colour
          FR: Choisir une couleur
      inputs:
        - type: LIST
          label:
            key: myCard.myAction.myInput1.label
            parameters:
              EN: Colours
              FR: Couleurs
          mandatory: true
          name: selectedColour
          value:
            value: '#000000'
            label:
              key: black
              parameters:
                EN: Paint It Black
                FR: Broyer du noir
          values:
            - value: '#000000'
              label:
                key: black
                parameters:
                  EN: Paint It Black
                  FR: Broyer du noir
            - value: '#51CE1E'
              label:
                key: green
                parameters:
                  EN: Go Green
                  FR: Se mettre au vert
        - type: LONGTEXT
          label:
            key: myCard.myAction.myInput2.label
            parameters:
              EN: Comment
              FR: Commentaire
          mandatory: false
          name: comment
          value: ''
          maxLength: 250
          rows: 10
          
  Input:
    description: Describe an input parameter for an Action
    type: object
    properties:
      type:
        $ref: '#/definitions/InputEnum'
        description: 'Parameter type, may imply some mandatory attributes, see description'
      label:
        $ref: '#/definitions/I18n'
        description: internationalized label
      mandatory:
        type: boolean
        default: false
        description: Is the parameter required
      name:
        type: string
        description: Parameter name (unique in action scope)
      value:
        type: string
        description: Parameter default value
      maxLength:
        type: integer
        description: >-
          Only for TEXT and LONGTEXT parameters. Specifies the maximum allowed
          character count
      rows:
        type: integer
        description: LONGTEXT parameter. Specifies the maximum number of displayed rows
      values:
        type: array
        description: >-
          Only for LIST,MULTI_LIST and SWITCH_LIST parameters. Specifies the
          selectable items in a list
        items:
          $ref: '#/definitions/ParameterListItem'
      selectedValues:
        type: array
        description: >-
          Only for MULTI_LIST and SWITCH_LIST parameters. List selected value.
          Order matters.
        items:
          type: string
      unSelectedValues:
        type: array
        description: >-
          Only for SWITCH_LIST parameters. List unselected values. Order
          matters.
        items:
          type: string
    required:
      - type
      - label
      - name
    example:
      type: LIST
      label:
        key: myCard.myAction.myInput.label
        parameters:
          EN: Colours
          FR: Couleurs
      mandatory: true
      name: selectedColour
      value:
        value: '#000000'
        label:
          key: black
          parameters:
            EN: Paint It Black
            FR: Broyer du noir
      values:
        - value: '#000000'
          label:
            key: black
            parameters:
              EN: Paint It Black
              FR: Broyer du noir
        - value: '#51CE1E'
          label:
            key: green
            parameters:
              EN: Go Green
              FR: Se mettre au vert
              
  ParameterListItem:
    description: An item of list input parameter
    type: object
    properties:
      value:
        type: string
        description: parameter technical value
      label:
        $ref: '#/definitions/I18n'
        description: Value i18n label
    required:
      - value
    example:
      value: 42
      label:
        key: the.answer
        parameters:
          EN: >-
            the Answer to the Ultimate Question of Life, the Universe, and
            Everything
          FR: 'la Réponse à la Grande Question sur la vie, l''Univers et le Reste'
